create database if not exists staff;
DROP DATABASE IF EXISTS staff;
CREATE DATABASE WIT;
USE WIT;
CREATE TABLE IF NOT EXISTS WIT.students(
NAME VARCHAR(26)NOT NULL,
STUD_ID INT PRIMARY KEY,
AGE INT,
MARKS INT,
STAFF_ID INT



);
SHOW TABLES;
SHOW COLUMNS FROM students;
 
 INSERT INTO  WIT.students(NAME,STUD_ID,AGE,MARKS) values
 ("Ishwaree",1,20,50),
 ("Sidhhi",2,19,30),
 ("Shubham",3,21,55),
 ("Shreya",4,22,45),
 ("Aditya",5,21,30),
 ("Raj",6,20,55);
 SHOW COLUMNS FROM WIT.students;
SELECT* FROM WIT.students;
CREATE TABLE IF NOT EXISTS WIT.STAFF_INFO(
STAFF_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
DEPT VARCHAR(30)
 );
 SHOW COLUMNS FROM WIT.STAFF_INFO;
 SELECT* FROM WIT.STAFF_INFO;
  INSERT INTO  WIT.STAFF_INFO( STAFF_ID,NAME,DEPT) values
  (101,"Dixit","CSE"),
  (102,"Avsekar","IT"),
  (103,"Kondekar","ENTC"),
  (104,"Patil","CIVIL");

 SELECT STAFF_ID FROM WIT.STAFF_INFO;
 SELECT NAME FROM WIT.STAFF_INFO;
 
 
SELECT *FROM WIT.students WHERE MARKS >50;

-- ADDING THE  COLUMN TO THE TABLE
ALTER TABLE WIT.students
ADD COLUMN STAFF_ID INT;


ALTER TABLE WIT.students
ADD CONSTRAINT fk_staff FOREIGN KEY (STAFF_ID)
    REFERENCES WIT.STAFF_INFO(STAFF_ID);
    
-- DISPLAYING THE  DISTINCT VALUES FROM THE TABLE
SELECT DISTINCT MARKS FROM WIT.students;
INSERT INTO WIT.students (NAME, STUD_ID, AGE, MARKS, STAFF_ID)
VALUES ('Raj', 6, 20, 65, NULL);
SELECT* FROM WIT.students;

-- ORDER BY ASCENDING OR DESCENDING 
SELECT DISTINCT MARKS FROM  WIT.students;
SELECT MARKS FROM WIT.students 
ORDER BY MARKS DESC;



-- SELECTING THE ID FROM STAFF_INFO USING ORDER BY CLAUSE
SELECT * FROM WIT.STAFF_INFO ORDER BY STAFF_ID DESC;
SELECT NAME,STUD_ID FROM WIT.students ORDER BY NAME,STUD_ID;
SELECT * FROM WIT.STAFF_INFO;
SELECT* FROM WIT.STAFF_INFO LIMIT 3;

SELECT* FROM WIT.STAFF_INFO LIMIT 0,4;

-- DLL COMMANDS
ALTER TABLE WIT.STAFF_INFO
ADD COLUMN SALARY INT;
SHOW COLUMNS FROM WIT.STAFF_INFO;

-- UPDATE COLUMN VALUES BY SET
UPDATE WIT.STAFF_INFO
SET SALARY = 2500 
WHERE STAFF_ID = 101;

UPDATE WIT.STAFF_INFO
SET SALARY = 3500 
WHERE STAFF_ID = 102;

UPDATE WIT.STAFF_INFO
SET SALARY = 4500 
WHERE STAFF_ID = 103;

UPDATE WIT.STAFF_INFO
SET SALARY = 5500 
WHERE STAFF_ID = 104;

SELECT * FROM WIT.STAFF_INFO;
DELETE FROM WIT.STAFF_INFO WHERE STAFF_ID=104;
SELECT * FROM WIT.STAFF_INFO;
SHOW COLUMNS FROM WIT.STAFF_INFO;


-- MODIFYING THE CONSTRAINTS
ALTER TABLE WIT.STAFF_INFO 
MODIFY COLUMN NAME VARCHAR (35) NULL;
SHOW COLUMNS FROM WIT.STAFF_INFO;


-- UNIQUE CONSTARINT 
ALTER TABLE WIT.STAFF_INFO
ADD CONSTRAINT unique_salary UNIQUE (SALARY);

-- PASSING NULL VALUES TO THE UNIQUE CONSTRAINT WILL SHOW ERROR
INSERT INTO WIT.STAFF_INFO (STAFF_ID,NAME,DEPT,SALARY) VALUES (106,"KULKARNI","MECH",NULL);
SELECT * FROM WIT.STAFF_INFO;

-- UPDATING THE COLUMN NAME AND DEPT
SELECT * FROM WIT.STAFF_INFO;
UPDATE WIT.STAFF_INFO
SET NAME = "KULKARNI"
WHERE STAFF_ID = 106;
SELECT * FROM WIT.STAFF_INFO;
UPDATE WIT.STAFF_INFO
SET DEPT = "CSE"
WHERE STAFF_ID = 106;
SELECT * FROM WIT.STAFF_INFO;


-- DROPING THE CONSTRAINTS
ALTER TABLE WIT.STAFF_INFO 
DROP INDEX unique_salary;
SHOW COLUMNS FROM WIT.STAFF_INFO;


