CREATE DATABASE EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE.EMP_INFO(
EMP_NO INT PRIMARY KEY,
ENAME VARCHAR(50) NOT NULL,
JOB VARCHAR(40),
HIREDATE DATE,
SALARY INT


);
ALTER TABLE EMP_INFO
MODIFY COLUMN HIREDATE DATE;
SHOW COLUMNS FROM EMPLOYEE.EMP_INFO;
-- 1
SELECT  JOB,ENAME,SALARY,HIREDATE FROM EMPLOYEE.EMP_INFO;
-- 2
SELECT ENAME AS EMPLOYEE_NAME, JOB AS JOB_TITLE, SALARY as MONTHLY_SALARY
FROM EMPLOYEE.EMP_INFO;
-- 3 RETRIVING THE 1 ST 5 EMPLOYEE COLUMNS ORDERING BY  SALARY IN DESCENDING ORDER 
SELECT * FROM EMPLOYEE.EMP_INFO ORDER BY SALARY DESC LIMIT 0,5;


-- RETRIVING THE PATTERNS USING LIKE 
SELECT ENAME FROM EMPLOYEE.EMP_INFO
WHERE ENAME LIKE '%AR%';
SELECT * FROM EMPLOYEE.EMP_INFO;