CREATE DATABASE TEMP_SCHEMA;
CREATE TABLE TEMP_SCHEMA.TABLE_1(
COL_STRING VARCHAR (355),
COL_NUM NUMERIC(10,2),
COL_DATE DATE
);
CREATE TABLE TEMP_SCHEMA.TABLE_2(
COL_NUM NUMERIC(10,2),
COL_STRING VARCHAR (355),
COL_DATE DATE
);
SELECT *FROM TEMP_SCHEMA.TABLE_2;
INSERT INTO TEMP_SCHEMA.TABLE_2
SELECT* FROM TEMP_SCHEMA.TABLE_1;
SELECT *FROM TEMP_SCHEMA.TABLE_2;
-- CREATE TABLE SCHEMA .TABLE AS (SELECT STATEMENT)
CREATE TABLE TEMP_SCHEMA.ctas_demo1 as SELECT * FROM TEMP_SCHEMA.TABLE1;
CREATE TABLE TEMP_SCHEMA.ctas_demo2 as SELECT COL_NUM FROM TEMP_SCHEMA.TABLE2;


/* ALTER TABLE  schema.table
Some action
EXAMPLES OF ACTION:
ADD COL_NAME DATATYPE
DROP COLUMN COL_NAME
MODIFY COLUMN COL_NAME DATATYPE
RENAME COLUMN  OLD COL_NAME TO NEW COL_NAME

-- CREATING 